module.exports ={
    systemSettings:{
        menus:{
            menuQuery:"menu_query",
            menuAdd:"menu_add",
            menuUp:"menu_up",
            menuDelte:"menu_delete",
        },
        user:{
            userQuery:"user_query",
            userAdd:"user_add",
            userUp:"user_up",
            userDelte:"user_delete",
            userPwd:"user_pwd",
        },
        role:{
            roleQuery:"role_query",
            roleAdd:"role_add",
            roleUp:"role_up",
            roleDelte:"role_delete"
        },
        more:{
            moreQuery:"more_query",
            moreAdd:"more_add",
            moreUp:"more_up",
            moreDelte:"more_delete"
        }
    }
}
